meu_projeto_dbt:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: '/content/meu_projeto_dbt/meu_banco.db'
      schema: main
      schema_directory: 'meu_projeto_dbt'
      schemas_and_paths:
        main: 'meu_banco.db'
        schema_directory: 'meu_projeto_dbt'